//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void ACMP1_enter_DefaultMode_from_RESET(void);
extern void DAC0_enter_DefaultMode_from_RESET(void);
extern void BURTC_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void OPAMP0_enter_DefaultMode_from_RESET(void);
extern void OPAMP1_enter_DefaultMode_from_RESET(void);
extern void OPAMP2_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void USART2_enter_DefaultMode_from_RESET(void);
extern void UART0_enter_DefaultMode_from_RESET(void);
extern void UART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void LEUART1_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void I2C1_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void TIMER2_enter_DefaultMode_from_RESET(void);
extern void TIMER3_enter_DefaultMode_from_RESET(void);
extern void LETIMER0_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PCNT1_enter_DefaultMode_from_RESET(void);
extern void PCNT2_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void ETM_enter_DefaultMode_from_RESET(void);
extern void EBI_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define BU_VIN_PIN          (8)
#define BU_VIN_PORT         (gpioPortD)

#define DUT0_AL_PIN         (8)
#define DUT0_AL_PORT        (gpioPortC)

#define DUT0_EN_PIN         (10)
#define DUT0_EN_PORT        (gpioPortC)

#define DUT0_WDI_PIN        (2)
#define DUT0_WDI_PORT       (gpioPortA)

#define DUT1_AL_PIN         (9)
#define DUT1_AL_PORT        (gpioPortC)

#define DUT1_EN_PIN         (11)
#define DUT1_EN_PORT        (gpioPortC)

#define DUT2_AL_PIN         (4)
#define DUT2_AL_PORT        (gpioPortE)

#define DUT2_EN_PIN         (6)
#define DUT2_EN_PORT        (gpioPortE)

#define DUT3_AL_PIN         (5)
#define DUT3_AL_PORT        (gpioPortE)

#define DUT3_EN_PIN         (7)
#define DUT3_EN_PORT        (gpioPortE)

#define HFXO_N_PIN          (14)
#define HFXO_N_PORT         (gpioPortB)

#define I2C0_SCL_PIN        (1)
#define I2C0_SCL_PORT       (gpioPortC)

#define I2C0_SDA_PIN        (0)
#define I2C0_SDA_PORT       (gpioPortC)

#define LED_PIN             (1)
#define LED_PORT            (gpioPortB)

#define LEUART0_RX_PIN      (15)
#define LEUART0_RX_PORT     (gpioPortE)

#define LEUART0_TX_PIN      (14)
#define LEUART0_TX_PORT     (gpioPortE)

#define LEUART1_RX_PIN      (7)
#define LEUART1_RX_PORT     (gpioPortC)

#define LEUART1_TX_PIN      (6)
#define LEUART1_TX_PORT     (gpioPortC)

#define LFXO_N_PIN          (8)
#define LFXO_N_PORT         (gpioPortB)

#define SD_CD_PIN           (3)
#define SD_CD_PORT          (gpioPortA)

#define SD_NCS_PIN          (6)
#define SD_NCS_PORT         (gpioPortB)

#define UART0_RX_PIN        (1)
#define UART0_RX_PORT       (gpioPortE)

#define UART0_TX_PIN        (0)
#define UART0_TX_PORT       (gpioPortE)

#define UART1_RX_PIN        (3)
#define UART1_RX_PORT       (gpioPortE)

#define UART1_TX_PIN        (2)
#define UART1_TX_PORT       (gpioPortE)

#define USART0_RX_PIN       (11)
#define USART0_RX_PORT      (gpioPortE)

#define USART0_TX_PIN       (10)
#define USART0_TX_PORT      (gpioPortE)

#define USART2_CLK_PIN      (5)
#define USART2_CLK_PORT     (gpioPortB)

#define USART2_RX_PIN       (4)
#define USART2_RX_PORT      (gpioPortB)

#define USART2_TX_PIN       (3)
#define USART2_TX_PORT      (gpioPortB)

// [User-defined pin name abstraction]$

#endif

